#!/bin/bash

module_file=`dirname $0`"/gitmodules"

echo -e $module_file


url=""
path=""
declare -i count
count=0
while read line
do
#    echo -e $line
    if [[ $line =~ "path = " ]]; then
        path=${line##*path = }
        count=0
    elif [[ $line =~ "url = " ]]; then
        url=${line##*url = }
        count=1
    else
        count=0
    fi

    if [ $count == 1 ]; then
        echo -e $path
        echo -e $url"\n"
        git submodule add $url $path
    fi

done < $module_file

