(progn
  (defun sw/push-mark()
    (unless (region-active-p)
      (push-mark (point))
      (push-mark (point))))
  ;; (defadvice etags-select-find (before mark-tag-before-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice etags-select-goto-tag (after mark-tag-after-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice org-footnote-new (before org-footnode-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice org-goto (before org-goto-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice org-open-at-point (before org-open-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice goto-line (after mark-goto-line-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice isearch-forward-regexp (after isearch-forward-regexp-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice isearch-backward-regexp (after isearch-backward-regexp-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice isearch-forward (after isearch-forward-regexp-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice isearch-backward (after isearch-backward-regexp-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice beginning-of-buffer (after beginning-of-buffer-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice end-of-buffer (after end-of-buffer-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice ace-jump-mode (after ace-jump-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice c-beginning-of-defun (after c-beginning-of-defun-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice c-end-of-defun (after c-end-of-defun-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice beginning-of-defun (after beginning-of-defun-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice end-of-defun (after end-of-defun-advice activate)
  ;;   (sw/push-mark))
  ;; (defadvice ahs-plugin-ahs-bod (around ahs-bod-advice activate)
  ;;   (ad-deactivate 'beginning-of-defun)
  ;;   (ad-deactivate 'end-of-defun)
  ;;   (ad-deactivate 'c-beginning-of-defun)
  ;;   (ad-deactivate 'c-end-of-defun)
  ;;   ad-do-it
  ;;   (ad-activate 'c-beginning-of-defun)
  ;;   (ad-activate 'c-end-of-defun))
  )
