(require 'openwith)
(openwith-mode t)
(when (eq system-type 'gnu/linux)
  (setq openwith-associations
        '(("\\.pdf$" "evince" (file))
          ("\\.mp3$" "mplayer" (file) )
          ("\\.mov\\|\\.RM$\\|\\.RMVB$\\|\\.avi$\\|\\.AVI$\\|\\.flv$\\|\\.mp4\\|\\.mkv$\\|\\.rmvb$\\|.wmv\\|.wav$" "mplayer" (file) )
          ;; ("\\.jpe?g$\\|\\.png$\\|\\.bmp\\|\\.gif$" "feh" (file))
	  ("\\.xlsx?$\\|\\.XLSX?$" "soffice"  (file) )
	  ("\\.doc[x]?$\\|\\.DOC[X]?$" "soffice"  (file) )
	  ("\\.ppt?$\\|\\.PPT?$" "soffice"  (file) )
          )
        )
  )
(when (eq system-type 'windows-nt)
  (setq openwith-associations
        '(("\\.pdf$" "open" (file)) ("\\.mp3$" "open" (file) )
          ("\\.mov\\|\\.RM$\\|\\.RMVB$\\|\\.avi$\\|\\.AVI$\\|\\.flv$\\|\\.mp4\\|\\.mkv$\\|\\.rmvb$" "open" (file) )
          ;; ("\\.jpe?g$\\|\\.png$\\|\\.bmp\\|\\.gif$" "open" (file))
          ("\\.CHM$\\|\\.chm$" "open"  (file) )
          )
        )
  )

;; (setq dired-guess-shell-alist-user
;;       `(
;; 	("\\(\\.gif$\\)\\|\\(\\.png$\\)\\|\\(\\.bmp$\\)\\|\\(\\.jpg$\\)\\|\\(\\.tif$\\)" "gthumb")
;; 	("\\(\\.avi$\\)\\|\\.mp4$\\|\\(\\.mkv$\\)\\|\\(\\.mpg$\\)\\|\\(\\.mpe?g$\\)\\|\\(\\.flv$\\)\\|\\(\\.wmv$\\)\\|\\(\\.mov$\\)\\|\\(\\.divx$\\)" " mplayer")
;; 	("\\(\\.wav$\\)\\|\\(\\.rm$\\)\\|\\(\\.rmvb$\\)\\|\\(\\.ra$\\)" " mplayer")
;; 	("\\.hd$" " mplayer -vo x11")
;; 	("\\.tar\\.bz2$" "tar jxvf")
;; 	("\\chm$" "chmsee")
;; 	("\\.torrent$" "ed2kopera")
;; 	("\\(\\.xls$\\)\\|\\(\\.doc$\\)\\|\\(\\.ppt$\\)" "soffice")
;; 	("\\.tar\\.gz$"  "tar zxvf")
;; 	("\\.tar$"   "tar xvf")
;; 	("\\(\\.rar$\\)\\|\\(\\.r[0-9]+$\\)" "unrar x")
;; 	("\\.htm[l]?$\\|.mht$" " google-chrome")
;; 	("\\.pdf$" " evince")
;; 	("\\.dvi$" " xdvi")
;; 	)
;;       )

(require 'mm-util)
(add-to-list 'mm-inhibit-file-name-handlers 'openwith-file-handler)
